services:
  back-end:
    container_name: pdfmanbackend
    image: pdfmanapp/pdfmanbackend:latest
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/PDFMAN
      FOLDER_PATH: /pdfs/
      THUMBNAIL_FOLDER: /thumbnails/
      PORT: 3001
      MEILISEARCH_API: http://localhost:7700
    ports:
      - "3001:3001"
    depends_on:
      - db

    volumes:
      - /path/to/pdfs/folder:/pdfs:rw
      - thumbnails:/thumbnails:rw
    restart:
      - always
  front-end:
    container_name: pdfmanfrontend
    image: pdfmanapp/pdfmanfrontend:latest
    ports:
      - "5173:80"
    environment:
      - API=http://localhost:3001/ # Ples replace localhost with local ip adress eg: 192.168.1.10
      - MEILISEARCH_URL= http://localhost:7700 
    depends_on:
      - back-end
  db:
    image: postgres
    container_name: postgresdb:17
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: PDFMAN
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  thumbnails:
