services:
  back-end:
    container_name: pdfmanbackend
    image: pdfmanapp/pdfmanbackend:latest
    shm_size: "4g"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/PDFMAN
      FOLDER_PATH: /pdfs/
      THUMBNAIL_FOLDER: /thumbnails/
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
      - migrator

    volumes:
      - /path/to/pdfs/folder:/pdfs:rw
      - thumbnails:/thumbnails:rw
    restart:
      - always
  front-end:
    container_name: pdfmanfrontend
    image: pdfmanapp/pdfmanfrontend:latest
    ports:
      - "5173:80"
    environment:
      - API=http://localhost:3001/ #if this is hosted on another device, you should put here its ip adress
    depends_on:
      - back-end
  db:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: PDFMAN
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrator:
    image: pdfmanapp/prismamigration:latest
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/PDFMAN
    depends_on:
      - db
    restart: no

volumes:
  pgdata:
  thumbnails:
